### ISSUE TITLE
Convention.MD의 Gitmoji 설명 추가 필요

### ISSUE THREAD

**Issue by jmkim648** [OrmiBandi/Devtail#2]
## 문제
현재 테이블에는 이모지, 태그 이름, 설명만 들어 있어 ```:   :``` 안에 어떤 문자를 넣어야 해당 이모지를 쓸 수 있는지 알 수 없습니다.
```이모지 | 이모지 코드 | 태그이름 | 설명```
식으로 수정이 필요할 듯 합니다.

**Comment by nayeongdev** [comment]
태그 테이블에 **이모지 코드** 컬럼을 추가해서 수정했습니다.
