### ISSUE TITLE
CONVENTION.md 목차 생성 필요

### ISSUE THREAD

**Issue by jmkim648** [OrmiBandi/Devtail#3]
1. 컨벤션의 내용이 제법 긴 편이고, 언어별/기능 별 찾아보기 위해서는 컨벤션 문서에도 목차가 필요할 것 같습니다.
다음과 같이 목차 부분을 추가해야할 필요가 있어보입니다.
```markdown
# 목차
[1.COMMIT 컨벤션](#commit-컨벤션)  
[2.코드 컨벤션](#코드-컨벤션)  
&ensp;[2-1. Python](#python-코드)  
&ensp;[2-2. HTML](#html)  
&ensp;[2-3. JavaScript](#javascript)  
```
2. HTML과 CSS가 h2로 취급되어 있는데, 개인적으로 CSS는 분량적으로도 비중 측면에서도 HTML에 통합되어 h3로 취급되는 것이 좋을 듯 합니다. ##을 ###으로 수정하는 것도 괜찮을 것 같습니다.

**Comment by hantang820** [comment]
59f8fe4f00cddeb86e85b8fa4e6259358a857679

**Comment by hantang820** [comment]
CONVENTION.md 파일 목차 추가하고 2-2. HTML 과 2-3. CSS 항목을 2-2. HTML/CSS로 병합했습니다!
